---
title: "FIRP Project Methodology"
author: "JMG"
format: docx
---


```{r}
#| message: false
#| include: false

library(tidyverse)
library(ggthemes)
library(scales)
library(latex2exp)

theme_set(theme_minimal(base_size=13))

update_geom_defaults("point", list(color = "midnightblue", alpha = 0.8))

source("R/infection_frequency.R")
```

## The Model


Average frequency of infection in the next generation is given by

$$
p_{t+1} = \frac{p_{t}F(1 - \mu)}{1 + p_{t}(F - 1 - s_{h}) + p_{t}^{2}s_{h}(1 - \mu F)},
$$

stochastic dynamics are given by

$$
q_{ij} = \left(\begin{array}{c} N \\ j \end{array}\right)(p^{\ast})^{j}(1 - p^{\ast})^{N - j}
$$




```{r}
#| label: fig-sim_example
#| fig-cap: A single simulation of the Turelli model, here $s_{h} = 0$.


p_0 <- 0.4
F_val_m <- 1.021
F_val_CV <- 0.4

mu_val <- 0.02
sh_val <- 0.0

N <- 1000

p <- turelli_simulation_p(p_0,F_val_m,F_val_CV,
                          sh_val,mu_val,N)

tibble(p=p) |>
  ggplot(aes(x=1:length(p),y=p)) +
  geom_point() +
  ylim(c(0,1)) + 
  labs(x = "Generation", y = "Frequency of infection")
```